using System.Globalization;
using System.IO;
using System.Text;
using UnityEngine;

/// <summary>
/// Lightweight OBJ file writer.
/// Writes a Unity Mesh to an ASCII .obj without any third-party dependency.
///
/// Coordinate systems:
///   Unity  - left-handed, Y-up  (x, y, z)
///   M&amp;B    - right-handed, Z-up  (x, z, y)
///
/// Pass swapYZ:true to remap Unity→M&amp;B: new pos = (x, z, y).
/// The swap also reverses face winding to preserve correct surface orientation
/// (swapping two axes reflects geometry, which flips triangle handedness).
/// </summary>
public static class ObjExporter
{
    /// <summary>
    /// Write a Mesh to an OBJ file. Creates parent directories automatically.
    /// </summary>
    /// <param name="mesh">Source Unity mesh.</param>
    /// <param name="outputPath">Absolute file path including filename, e.g. ".../ScoData/ai_mesh.obj".</param>
    /// <param name="objectName">Optional override for the 'o' name line (defaults to mesh.name).</param>
    /// <param name="swapYZ">
    ///   When true, converts Unity (Y-up left-handed) → M&amp;B (Z-up right-handed):
    ///   vertex/normal (x,y,z) is written as (x,z,y) and face winding is reversed.
    /// </param>
    public static void Export(Mesh mesh, string outputPath, string objectName = null, bool swapYZ = false)
    {
        if (mesh == null)
            throw new System.ArgumentNullException(nameof(mesh));

        string dir = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(dir))
            Directory.CreateDirectory(dir);

        var ci  = CultureInfo.InvariantCulture;
        var sb  = new StringBuilder(256 * 1024);

        Vector3[] verts   = mesh.vertices;
        Vector3[] normals = mesh.normals;
        Vector2[] uvs     = mesh.uv;
        int[]     tris    = mesh.triangles;

        bool hasNormals = normals != null && normals.Length == verts.Length;
        bool hasUV      = uvs     != null && uvs.Length     == verts.Length;

        sb.AppendLine("# M&B NavMesh AI Mesh Export – generated by MBToolset");
        sb.AppendFormat(ci, "# Vertices: {0}   Triangles: {1}\n", verts.Length, tris.Length / 3);
        if (swapYZ) sb.AppendLine("# Coordinate system: Unity Y-up → M&B Z-up (Y↔Z swap applied)");
        sb.AppendLine();
        sb.AppendLine($"o {objectName ?? mesh.name}");
        sb.AppendLine();

        // When swapYZ is true: Unity (x,y,z) → M&B (x,z,y)
        foreach (var v in verts)
        {
            if (swapYZ) sb.AppendFormat(ci, "v {0:G7} {1:G7} {2:G7}\n", v.x, v.z, v.y);
            else        sb.AppendFormat(ci, "v {0:G7} {1:G7} {2:G7}\n", v.x, v.y, v.z);
        }

        sb.AppendLine();

        if (hasNormals)
        {
            foreach (var n in normals)
            {
                if (swapYZ) sb.AppendFormat(ci, "vn {0:G7} {1:G7} {2:G7}\n", n.x, n.z, n.y);
                else        sb.AppendFormat(ci, "vn {0:G7} {1:G7} {2:G7}\n", n.x, n.y, n.z);
            }
            sb.AppendLine();
        }

        if (hasUV)
        {
            foreach (var u in uvs)
                sb.AppendFormat(ci, "vt {0:G7} {1:G7}\n", u.x, u.y);
            sb.AppendLine();
        }

        // Swapping Y↔Z reflects geometry (changes handedness), so we reverse
        // winding order (a,b,c → a,c,b) to keep normals pointing outward.
        sb.AppendLine("g ai_mesh");

        for (int t = 0; t < tris.Length; t += 3)
        {
            // Original order: a, b, c - reflected order: a, c, b
            int a = tris[t]     + 1;
            int b = swapYZ ? tris[t + 2] + 1 : tris[t + 1] + 1;
            int c = swapYZ ? tris[t + 1] + 1 : tris[t + 2] + 1;

            if (hasUV && hasNormals)
                sb.AppendFormat("f {0}/{0}/{0} {1}/{1}/{1} {2}/{2}/{2}\n", a, b, c);
            else if (hasUV)
                sb.AppendFormat("f {0}/{0} {1}/{1} {2}/{2}\n", a, b, c);
            else if (hasNormals)
                sb.AppendFormat("f {0}//{0} {1}//{1} {2}//{2}\n", a, b, c);
            else
                sb.AppendFormat("f {0} {1} {2}\n", a, b, c);
        }

        File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
    }
}
