using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEditor;
using Unity.Collections;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Jobs;
using Unity.Burst;
using Unity.Mathematics;

/// <summary>
/// MBTerrainDecorator
/// 
/// Optimizations:
/// 1. Unity Job System for parallel processing
/// 2. Burst compilation for hot paths
/// 3. Cached height/splatmap data instead of per-pixel reads
/// 4. NativeArrays for better memory access patterns
/// 5. Batched progress updates
/// 6. Pre-calculated slope map using Horn's algorithm 
/// 7. Pre-calculated curvature maps using Zeverbergen & Thorne algorithm 
/// </summary>
public class MBTerrainDecorator : MonoBehaviour
{
    public enum FilterType { height, slope, curvature, noise, texture, layer, pgm, generator, warband,
        waterLevel
    }
    public enum BlendType { normal, add, sub, mul, max, min, occlusion }
    public enum ImageChannel { r, g, b, a }
    public enum LayerType { texture, tree }
    
    /// <summary>
    /// Determines which processing block a layer belongs to.
    /// Base = auto-generated engine-accurate layers (rebuilt by regenerator, not user-editable).
    /// Overlay = user hand-painted layers that persist across regenerations.
    /// </summary>
    public enum LayerBlock { Base, Overlay }
    
    /// <summary>
    /// How overlay layers blend onto the base splatmap result.
    /// </summary>
    public enum OverlayBlendMode
    {
        /// <summary>Adds overlay weight, then renormalizes.</summary>
        Additive,
        /// <summary>Lerps between base and overlay based on opacity.</summary>
        Lerp,
        /// <summary>Replaces base channels where overlay has weight.</summary>
        Replace,
        /// <summary>Painter's algorithm: overlay occludes base proportionally.</summary>
        PainterOcclusion
    }
    
    public enum NormalizationMode
    {
        SimpleNormalize,
        MBPainterAlgorithm,
        MBNormalized,
        /// <summary>Write raw weights without any normalization. Used internally for overlay pass.</summary>
        RawPassthrough
    }

    public Terrain t;
    
    [System.Serializable]
    public class Layers
    {
        public string name;
        public bool active;
        public int layerIndex;
        public LayerType layerType;
        
        /// <summary>
        /// Which processing block this layer belongs to.
        /// Base = auto-generated by regenerator (locked, rebuilt on regeneration).
        /// Overlay = user hand-painted (persists across regenerations).
        /// </summary>
        public LayerBlock block = LayerBlock.Base;
        
        /// <summary>
        /// How this overlay layer blends onto the base splatmap.
        /// Only used when block == Overlay.
        /// </summary>
        public OverlayBlendMode overlayBlendMode = OverlayBlendMode.PainterOcclusion;
        
        /// <summary>
        /// Master opacity for overlay layers (0-1).
        /// Only used when block == Overlay.
        /// </summary>
        [Range(0f, 1f)]
        public float overlayOpacity = 1f;
        
        /// <summary>
        /// If true, this overlay layer was manually created by the user and 
        /// will be preserved across regeneration. Auto-generated overlay layers
        /// (from SetupDecoratorFromHash) have this set to false and are rebuilt each time.
        /// </summary>
        public bool isUserCreated = false;
        
        public float probability;
        public int maximumTreeCount;
        public int treeCount;
        
        public float width;
        public float height;
        
        public float randomPosition;
        public float randomRotation;
        public float randomSize;
        public float randomHealth;
        
        public float offset;
        
        public float debugLayerWeight;
        public float resultWeight;
        public float debugResultWeight;
        public float correctedResultWeight;
        public float debugCorrectedResultWeight;
        
        public List<Rules> rules = new List<Rules>();
        public int activeRuleCount = 0;
    }
    
    [System.Serializable]
    public class Rules
    {
        public bool active;
        public FilterType filter;
        public float min;
        public float max;
        public float frequency;
        public float lacunarity;
        public int perlinOctaves;
        
        public float intensity = 1;
        public float contrast;
        public Texture2D texture;
        public DefaultAsset pgmAsset;
        public TextAsset generatorAsset;
        public ImageChannel imageChannel;
        public int targetLayerIndex;
        
        // Curvature-specific settings
        [Tooltip("Type of curvature to use: Standard (ridges/valleys), Profile (flow acceleration), Plan (flow convergence)")]
        public CurvatureCalculator.CurvatureType curvatureType = CurvatureCalculator.CurvatureType.Standard;
        
        [System.NonSerialized]
        public Color[] map;
        
        [System.NonSerialized]
        public NativeArray<float> nativeMap;
        
        public BlendType blend;
        public float weight;
        
        public float debugWeight;
        public bool invert;
        public bool useShorelineDistance;
        public float maxShorelineDistance;
    }
    
    [HideInInspector]
    public List<Layers> layers = new List<Layers>();
    
    public float fallOffDistance = 2;
    public bool fallOfNoise = true;
    // public int perlinOctaves = 5;
    public bool clearTexture = true;
    public bool clearTrees = true;
    
    public Vector2Int debugPos;
    
    public float fallofNoiseFrequency = 150f;
    public float fallofNoiseContrast = 10f;
    public float fallofNoiseAmplitude = 1f;
    
    [Header("M&B Compatibility")]
    public NormalizationMode normalizationMode = NormalizationMode.MBNormalized;
    public float visibilityThreshold = 0.01f;
    
    [Header("Overlay Block")]
    [Tooltip("Renormalize splatmap after overlay compositing")]
    public bool renormalizeAfterOverlay = true;

    [Header("Vegetation Mask")]
    [Tooltip("Global mask texture that punches through overlay layers to reveal base terrain underneath")]
    public Texture2D vegetationMaskTexture;
    
    [Tooltip("Which channel of the vegetation mask texture to read")]
    public ImageChannel vegetationMaskChannel = ImageChannel.r;
    
    [Tooltip("Overall strength of the vegetation mask (0 = no effect, 1 = full punch-through)")]
    [Range(0f, 1f)]
    public float vegetationMaskStrength = 1f;
    
    [Tooltip("Invert the vegetation mask")]
    public bool vegetationMaskInvert = false;
    
    /// <summary>
    /// Cached vegetation mask data, sampled at alphamap resolution.
    /// Populated during Decorate() if vegetationMaskTexture is assigned.
    /// </summary>
    [System.NonSerialized]
    private float[] cachedVegetationMask;

    [Header("Optimization Settings")]
    [Tooltip("Use Unity Job System for parallel processing")]
    public bool useJobSystem = true;
    
    [Tooltip("Batch size for job processing")]
    public int jobBatchSize = 64;
    
    [Tooltip("Update progress every N rows")]
    public int progressUpdateInterval = 100;

    [Header("Slope Calculation")]
    [Tooltip("Use Horn's algorithm for accurate slope calculation")]
    public bool useAccurateSlope = true;
    
    [Tooltip("Cache slope map for faster repeated access")]
    public bool cacheSlopeMap = true;
    
    [Tooltip("Use bilinear interpolation for smoother slope values")]
    public bool interpolateSlope = false;
    
    [Tooltip("Slope values are in degrees (0-90) when true, normalized (0-1) when false")]
    public bool slopeInDegrees = true;

    [Header("Curvature Calculation")]
    [Tooltip("Use Zeverbergen & Thorne algorithm for curvature")]
    public bool useAccurateCurvature = true;
    
    [Tooltip("Cache curvature maps for faster repeated access")]
    public bool cacheCurvatureMap = true;
    
    [Tooltip("Use bilinear interpolation for smoother curvature values")]
    public bool interpolateCurvature = false;
    
    [Tooltip("Curvature values are normalized (0-1) when true, raw values when false")]
    public bool curvatureNormalized = true;

    [Header("Water Level Calculation")]
    [Tooltip("Cache shoreline distance map before decoration for faster per-pixel access")]
    public bool cacheWaterMap = true;

    public int textureLayerCount = 0;
    private int treePrototypeCount = 0;
    private int alphamapWidth = 0;
    private int alphamapHeight = 0;
    private int heightMapWidth = 0;
    private int heightMapHeight = 0;
    
    // Cached data for optimization
    private NativeArray<float> cachedHeights;
    private NativeArray<float> cachedSplatmaps;
    private NativeArray<float> cachedSlopes;
    private NativeArray<float> cachedCurvatureStandard;
    private NativeArray<float> cachedCurvatureProfile;
    private NativeArray<float> cachedCurvaturePlan;
    private NativeArray<float> cachedWaterShoreDistances;
    private NativeArray<float> outputSplatmap;
    
    // Cached slope map (managed version for sequential path)
    private MBTerrainDecoratorSlopeExtensions.CachedSlopeMap slopeCache;
    
    // Cached curvature map (managed version for sequential path)
    private MBTerrainDecoratorCurvatureExtensions.CachedCurvatureMap curvatureCache;
    
    // Cached water level map (managed version for sequential path)
    private MBTerrainDecoratorWaterExtensions.CachedWaterMap waterCache;
    
    // Terrain geometry for slope/curvature calculation
    private float cellSizeX;
    private float cellSizeY;
    private float cellSize; // Average for curvature
    private float heightScale;
    
    float[,,] map;
    public bool showProgress;
    public bool calculating = false;
    public float calculatingPercent;
    
    public bool debugMode = false;
    public float waterLevel;

    void OnEnable()
    {
        t = GetComponent<Terrain>();
    }
    
    void Start()
    {
        t = GetComponent<Terrain>();
    }
    
    public Terrain GetTerrain()
    {
        t = GetComponent<Terrain>();
        return t;
    }

    #region Slope Calculation
    
    /// <summary>
    /// Pre-calculate slope map for the terrain using Horn algorithm.
    /// Call this before decoration if using cached slope mode.
    /// </summary>
    public void PreCalculateSlopeMap()
    {
        if (t == null || t.terrainData == null) return;
        
        slopeCache = MBTerrainDecoratorSlopeExtensions.CachedSlopeMap.Create(
            t.terrainData, useJobSystem);
        
        Debug.Log($"[MBTerrainDecorator] Slope map pre-calculated: {slopeCache.Width}x{slopeCache.Height}");
    }
    
    /// <summary>
    /// Clear the cached slope map to free memory.
    /// </summary>
    public void ClearSlopeCache()
    {
        slopeCache = null;
    }
    
    /// <summary>
    /// Get slope at a normalized position using the configured method.
    /// </summary>
    /// <param name="normX">Normalized X position (0-1)</param>
    /// <param name="normY">Normalized Y position (0-1)</param>
    /// <returns>Slope value (degrees or normalized based on slopeInDegrees setting)</returns>
    public float GetSlopeAt(float normX, float normY)
    {
        if (!useAccurateSlope)
        {
            // Legacy Unity GetSteepness method
            return t.terrainData.GetSteepness(normY, normX) / (slopeInDegrees ? 1f : 90f);
        }
        
        if (cacheSlopeMap && slopeCache != null)
        {
            if (interpolateSlope)
                return slopeCache.GetSlopeAtInterpolated(normX, normY, slopeInDegrees);
            else
                return slopeCache.GetSlopeAt(normX, normY, slopeInDegrees);
        }
        
        // Direct calculation (slower but doesn't require pre-calculation)
        float[,] heights = t.terrainData.GetHeights(0, 0, heightMapWidth, heightMapHeight);
        float slope = MBTerrainDecoratorSlopeExtensions.CalculateSlopeAtNormalizedPosition(
            heights, normX, normY, cellSizeX, cellSizeY, heightScale);
        
        return slopeInDegrees ? slope : slope / 90f;
    }
    
    /// <summary>
    /// Calculate slope weight for decoration rules.
    /// </summary>
    public float CalculateSlopeWeight(float normX, float normY, float min, float max)
    {
        float slope = GetSlopeAt(normX, normY);
        return CalculateWeigth(slope, min, max, fallOffDistance / 100f);
    }
    
    #endregion

    #region Curvature Calculation
    
    /// <summary>
    /// Pre-calculate curvature maps for the terrain
    /// Call this before decoration if using cached curvature mode.
    /// </summary>
    public void PreCalculateCurvatureMap()
    {
        if (t == null || t.terrainData == null) return;
        
        curvatureCache = MBTerrainDecoratorCurvatureExtensions.CachedCurvatureMap.Create(
            t.terrainData, useJobSystem);
        
        Debug.Log($"[MBTerrainDecorator] Curvature maps pre-calculated: {curvatureCache.Width}x{curvatureCache.Height}");
        Debug.Log($"  Standard range: [{curvatureCache.Statistics.MinStandard:F2}, {curvatureCache.Statistics.MaxStandard:F2}]");
        Debug.Log($"  Profile range: [{curvatureCache.Statistics.MinProfile:F2}, {curvatureCache.Statistics.MaxProfile:F2}]");
        Debug.Log($"  Plan range: [{curvatureCache.Statistics.MinPlan:F2}, {curvatureCache.Statistics.MaxPlan:F2}]");
    }
    
    /// <summary>
    /// Clear the cached curvature maps to free memory.
    /// </summary>
    public void ClearCurvatureCache()
    {
        curvatureCache = null;
    }
    
    /// <summary>
    /// Get curvature at a normalized position using the configured method.
    /// </summary>
    /// <param name="normX">Normalized X position (0-1)</param>
    /// <param name="normY">Normalized Y position (0-1)</param>
    /// <param name="type">Type of curvature to retrieve</param>
    /// <returns>Curvature value (normalized 0-1 or raw based on curvatureNormalized setting)</returns>
    public float GetCurvatureAt(float normX, float normY, CurvatureCalculator.CurvatureType type = CurvatureCalculator.CurvatureType.Standard)
    {
        if (!useAccurateCurvature)
        {
            // No legacy fallback for curvature - use cached or direct calculation
            return 0.5f; // Neutral value
        }
        
        if (cacheCurvatureMap && curvatureCache != null)
        {
            if (interpolateCurvature)
                return curvatureCache.GetCurvatureAtInterpolated(normX, normY, type, curvatureNormalized);
            else
                return curvatureCache.GetCurvatureAt(normX, normY, type, curvatureNormalized);
        }
        
        // Direct calculation (slower but doesn't require pre-calculation)
        float[,] heights = t.terrainData.GetHeights(0, 0, heightMapWidth, heightMapHeight);
        var result = CurvatureCalculator.CalculateAtNormalizedPosition(
            heights, normX, normY, cellSize, heightScale);
        
        float rawValue = result.Get(type);
        
        if (curvatureNormalized)
        {
            // Normalize using typical range (-50 to 50)
            return Mathf.Clamp01((rawValue + 50f) / 100f);
        }
        
        return rawValue;
    }
    
    /// <summary>
    /// Calculate curvature weight for decoration rules.
    /// </summary>
    public float CalculateCurvatureWeight(float normX, float normY, float min, float max, 
        CurvatureCalculator.CurvatureType type = CurvatureCalculator.CurvatureType.Standard)
    {
        float curvature = GetCurvatureAt(normX, normY, type);
        return CalculateWeigth(curvature, min, max, fallOffDistance / 100f);
    }
    
    #endregion

    #region Water Level Calculation

    /// <summary>
    /// Pre-calculate water level and shoreline distance map for the terrain.
    /// Call this before decoration if using cached water map mode.
    /// </summary>
    public void PreCalculateWaterMap()
    {
        if (t == null || t.terrainData == null) return;

        waterCache = MBTerrainDecoratorWaterExtensions.CachedWaterMap.Create(
            t.terrainData, transform.position.y, waterLevel,
            maxDistance: 200f, useParallel: useJobSystem);

        Debug.Log($"[MBTerrainDecorator] Water map pre-calculated: {waterCache.Width}x{waterCache.Height}, " +
                  $"underwater={waterCache.Statistics.UnderwaterPercentage:F1}%, " +
                  $"edges={waterCache.Statistics.EdgeCellCount}");
    }

    /// <summary>
    /// Clear the cached water map to free memory.
    /// </summary>
    public void ClearWaterCache()
    {
        waterCache = null;
    }

    /// <summary>
    /// Check if any active rules use the waterLevel filter.
    /// </summary>
    private bool HasWaterLevelRules()
    {
        foreach (var layer in layers)
        {
            if (!layer.active) continue;
            foreach (var rule in layer.rules)
            {
                if (rule.active && rule.filter == FilterType.waterLevel)
                    return true;
            }
        }
        return false;
    }

    /// <summary>
    /// Calculate water-level-based decoration weight for the sequential path.
    /// Uses the cached water map if available, otherwise falls back to direct calculation.
    /// </summary>
    public float CalculateWaterLevelWeight(float normX, float normY, float min, float max,
                                            bool useShoreline, float maxShoreDist)
    {
        if (waterCache != null)
            return MBTerrainDecoratorWaterExtensions.CalculateWaterWeight(
                waterCache, normX, normY, min, max, fallOffDistance / 100f, useShoreline, maxShoreDist);

        // Fallback: direct calculation (no cache)
        float[,] h = t.terrainData.GetHeights(0, 0, heightMapWidth, heightMapHeight);
        return MBTerrainDecoratorWaterExtensions.CalculateWaterWeight(
            h, normX, normY, min, max, fallOffDistance / 100f,
            transform.position.y, heightScale, waterLevel);
    }

    #endregion

    #region Optimized Job Structs
    
    /// <summary>
    /// Burst-compiled job for processing terrain decoration in parallel.
    /// Uses NativeDisableParallelForRestriction since each pixel writes to a unique range.
    /// </summary>
    [BurstCompile(FloatPrecision.Standard, FloatMode.Fast)]
    public struct DecorateJob : IJobParallelFor
    {
        [ReadOnly] public int alphamapWidth;
        [ReadOnly] public int alphamapHeight;
        [ReadOnly] public int heightMapWidth;
        [ReadOnly] public int heightMapHeight;
        [ReadOnly] public int textureLayerCount;
        [ReadOnly] public float fallOffDistance;
        [ReadOnly] public NormalizationMode normMode;
        [ReadOnly] public float visibilityThreshold;
        
        // Slope calculation parameters
        [ReadOnly] public bool useAccurateSlope;
        [ReadOnly] public float cellSizeX;
        [ReadOnly] public float cellSizeY;
        [ReadOnly] public float heightScale;
        [ReadOnly] public bool slopeInDegrees;
        
        // Curvature calculation parameters
        [ReadOnly] public bool useAccurateCurvature;
        [ReadOnly] public float cellSize; // Average for curvature
        [ReadOnly] public bool curvatureNormalized;
        
        // Water level parameters
        [ReadOnly] public float waterLevel;
        [ReadOnly] public float terrainY;
        [ReadOnly] public NativeArray<float> waterShoreDistances;
        
        [ReadOnly] public NativeArray<float> heights;
        [ReadOnly] public NativeArray<float> slopes; // Pre-calculated slope map
        [ReadOnly] public NativeArray<float> curvatureStandard; // Pre-calculated curvature maps
        [ReadOnly] public NativeArray<float> curvatureProfile;
        [ReadOnly] public NativeArray<float> curvaturePlan;
        [ReadOnly] public NativeArray<float> existingSplatmaps;
        
        // Rule data - flattened for job access
        [ReadOnly] public NativeArray<RuleData> ruleData;
        [ReadOnly] public NativeArray<int> layerRuleOffsets;
        [ReadOnly] public NativeArray<int> layerRuleCounts;
        [ReadOnly] public NativeArray<int> layerIndices;
        [ReadOnly] public NativeArray<bool> layerActive;
        
        // Rule maps - all concatenated
        [ReadOnly] public NativeArray<float> allRuleMaps;
        [ReadOnly] public NativeArray<int> ruleMapOffsets;
        [ReadOnly] public NativeArray<int> ruleMapSizes;
        
        // Output - disable safety restriction since each pixel writes to unique indices
        [NativeDisableContainerSafetyRestriction]
        public NativeArray<float> outputSplatmap;
        
        public void Execute(int pixelIndex)
        {
            int x = pixelIndex % alphamapWidth;
            int y = pixelIndex / alphamapWidth;
            
            float normX = x / (float)(alphamapWidth - 1);
            float normY = y / (float)(alphamapHeight - 1);
            
            // Use stack-allocated array for small fixed-size data (max 32 layers)
            const int MAX_LAYERS = 32;
            var rawWeights = new NativeArray<float>(math.min(textureLayerCount, MAX_LAYERS), Allocator.Temp);
            
            // Zero initialize
            for (int i = 0; i < rawWeights.Length; i++)
                rawWeights[i] = 0f;
            
            int decoratorLayerCount = layerActive.Length;
            for (int layerNo = 0; layerNo < decoratorLayerCount; layerNo++)
            {
                if (!layerActive[layerNo]) continue;
                int targetIdx = layerIndices[layerNo];
                if (targetIdx >= textureLayerCount || targetIdx >= rawWeights.Length) continue;
                
                float layerWeight = ProcessLayerRules(layerNo, x, y, normX, normY);
                rawWeights[targetIdx] += layerWeight;
            }
            
            // Convert to splatmap weights and write directly to output
            ConvertAndWriteSplatmapWeights(rawWeights, pixelIndex);
            
            rawWeights.Dispose();
        }
        
        private float ProcessLayerRules(int layerNo, int x, int y, float normX, float normY)
        {
            int ruleOffset = layerRuleOffsets[layerNo];
            int ruleCount = layerRuleCounts[layerNo];
            
            float layerResultWeight = 0f;
            bool firstRule = true;
            
            for (int i = 0; i < ruleCount; i++)
            {
                RuleData rule = ruleData[ruleOffset + i];
                if (!rule.active) continue;
                
                float weight = EvaluateRule(rule, ruleOffset + i, x, y, normX, normY);
                
                // Apply intensity and contrast
                if (rule.intensity < 0)
                    weight = 1 - weight;
                
                weight = (weight - 0.5f) * (rule.contrast + 1) + 0.5f;
                weight *= math.abs(rule.intensity);
                weight = math.clamp(weight, 0, 1);
                
                // Apply blend
                if (firstRule)
                {
                    layerResultWeight = weight;
                    firstRule = false;
                }
                else
                {
                    layerResultWeight = ApplyBlend(layerResultWeight, weight, rule.blend);
                }
            }
            
            return math.clamp(layerResultWeight, 0f, 1f);
        }
        
        private float EvaluateRule(RuleData rule, int globalRuleIndex, int x, int y, float normX, float normY)
        {
            float weight = 0f;
            
            switch (rule.filter)
            {
                case FilterType.height:
                    int hx = math.clamp((int)(normX * (heightMapHeight - 1)), 0, heightMapHeight - 1);
                    int hy = math.clamp((int)(normY * (heightMapWidth - 1)), 0, heightMapWidth - 1);
                    float heightVal = heights[hx * heightMapWidth + hy];
                    weight = CalculateWeight(heightVal, rule.min, rule.max, fallOffDistance / 100f);
                    break;
                    
                case FilterType.slope:
                    weight = CalculateSlopeWeightBurst(normX, normY, rule.min, rule.max);
                    break;
                    
                case FilterType.curvature:
                    weight = CalculateCurvatureWeightBurst(normX, normY, rule.min, rule.max, rule.curvatureType);
                    break;
                    
                case FilterType.noise:
                    weight = ProPerlinBurst(normY, normX, rule.frequency, rule.lacunarity, rule.perlinOctaves);
                    break;
                    
                case FilterType.texture:
                case FilterType.pgm:
                case FilterType.generator:
                case FilterType.warband:
                    int mapOffset = ruleMapOffsets[globalRuleIndex];
                    int mapSize = ruleMapSizes[globalRuleIndex];
                    if (mapSize > 0)
                    {
                        int idx = x + y * alphamapWidth;
                        if (idx < mapSize)
                        {
                            weight = allRuleMaps[mapOffset + idx];
                        }
                    }
                    break;
                    
                case FilterType.layer:
                    if (rule.targetLayerIndex < textureLayerCount)
                    {
                        int splatIdx = (x + y * alphamapWidth) * textureLayerCount + rule.targetLayerIndex;
                        if (splatIdx < existingSplatmaps.Length)
                        {
                            weight = existingSplatmaps[splatIdx];
                        }
                    }
                    break;
                    
                case FilterType.waterLevel:
                    weight = CalculateWaterWeightBurst(normX, normY, rule.min, rule.max,
                                                       rule.useShorelineDistance, rule.maxShorelineDistance);
                    break;
                
            }
            if (rule.invert)
                weight = 1f - weight;
            
            return weight;
        }
        
        private float CalculateWaterWeightBurst(float normX, float normY, float min, float max,
                                                  bool useShoreline, float maxShoreDist)
        {
            // Use pre-calculated shoreline distances if available
            NativeArray<float> shores = (useShoreline && waterShoreDistances.IsCreated && waterShoreDistances.Length > 0)
                ? waterShoreDistances : default;
            
            return MBTerrainDecoratorWaterExtensions.CalculateWaterWeightWithShorelineBurst(
                heights, shores,
                heightMapWidth, heightMapHeight,
                normX, normY,
                min, max, fallOffDistance / 100f,
                terrainY, heightScale, waterLevel,
                useShoreline ? maxShoreDist : 0f);
        }
        
        private float CalculateSlopeWeightBurst(float normX, float normY, float min, float max)
        {
            float slope;
            
            if (useAccurateSlope && slopes.IsCreated && slopes.Length > 0)
            {
                // Use pre-calculated slope map
                int sx = math.clamp((int)(normX * (heightMapWidth - 1)), 0, heightMapWidth - 1);
                int sy = math.clamp((int)(normY * (heightMapHeight - 1)), 0, heightMapHeight - 1);
                slope = slopes[sy * heightMapWidth + sx];
                
                // Convert to normalized if needed
                if (!slopeInDegrees)
                    slope = slope / 90f;
            }
            else
            {
                // Fallback: calculate slope directly using Horn's algorithm
                slope = MBTerrainDecoratorSlopeExtensions.CalculateSlopeBurst(
                    heights, heightMapWidth, heightMapHeight,
                    normX, normY, cellSizeX, cellSizeY, heightScale);
                
                if (!slopeInDegrees)
                    slope = slope / 90f;
            }
            
            return CalculateWeight(slope, min, max, fallOffDistance / 100f);
        }
        
        private float CalculateCurvatureWeightBurst(float normX, float normY, float min, float max, int curvatureType)
        {
            float curvature;
            
            // Select appropriate curvature map
            NativeArray<float> curvatureMap;
            switch (curvatureType)
            {
                case 1: // Profile
                    curvatureMap = curvatureProfile;
                    break;
                case 2: // Plan
                    curvatureMap = curvaturePlan;
                    break;
                default: // Standard
                    curvatureMap = curvatureStandard;
                    break;
            }
            
            if (useAccurateCurvature && curvatureMap.IsCreated && curvatureMap.Length > 0)
            {
                // Use pre-calculated curvature map (already normalized)
                int cx = math.clamp((int)(normY * (heightMapWidth - 1)), 0, heightMapWidth - 1);
                int cy = math.clamp((int)(normX * (heightMapHeight - 1)), 0, heightMapHeight - 1);
                curvature = curvatureMap[cy * heightMapWidth + cx];
            }
            else
            {
                // Fallback: calculate curvature directly
                curvature = MBTerrainDecoratorCurvatureExtensions.CalculateCurvatureWeightBurst(
                    heights, heightMapWidth, heightMapHeight,
                    normX, normY, 0f, 1f, 0.0001f,
                    cellSize, heightScale, curvatureType);
            }
            
            return CalculateWeight(curvature, min, max, fallOffDistance / 100f);
        }
        
        private float CalculateWeight(float val, float min, float max, float falloff)
        {
            if (falloff < 0.0001f) falloff = 0.0001f;
            
            float weight;
            if (val > min + falloff / 2f && val <= max - falloff / 2f)
            {
                weight = 1f;
            }
            else if (val < min + falloff / 2f)
            {
                weight = (val - (min - falloff / 2f)) / falloff;
            }
            else
            {
                weight = 1f - (val - (max - falloff / 2f)) / falloff;
            }
            
            return math.clamp(weight, 0f, 1f);
        }
        
        private float ProPerlinBurst(float x, float y, float frequency, float lacunarity, int octaves)
        {
            float total = 0;
            float freq = frequency;
            float amplitude = 1f;
            float persistence = 0.5f;
            float totalAmplitude = 0;
            
            for (int i = 0; i < octaves; i++)
            {
                // Use Unity.Mathematics noise
                float noiseVal = noise.cnoise(new Unity.Mathematics.float2(x * freq, y * freq));
                total += (noiseVal * 0.5f + 0.5f) * amplitude;
                totalAmplitude += amplitude;
                amplitude *= persistence;
                freq *= lacunarity;
            }
            
            return total / math.max(totalAmplitude, 0.0001f);
        }
        
        private float ApplyBlend(float current, float newVal, BlendType blend)
        {
            switch (blend)
            {
                case BlendType.normal: return newVal; 
                case BlendType.add: return current + newVal;
                case BlendType.sub: return current - newVal;
                case BlendType.mul: return current * newVal;
                case BlendType.min: return math.min(current, newVal);
                case BlendType.max: return math.max(current, newVal);
                case BlendType.occlusion:
                    float occluded = current * (1f - newVal);
                    return math.clamp(occluded + newVal, 0, 1);
                default: return current;
            }
        }
        
        private void ConvertAndWriteSplatmapWeights(NativeArray<float> rawWeights, int pixelIndex)
        {
            int count = rawWeights.Length;
            int outputOffset = pixelIndex * textureLayerCount;
            
            switch (normMode)
            {
                case NormalizationMode.SimpleNormalize:
                {
                    float total = 0f;
                    for (int i = 0; i < count; i++)
                        total += rawWeights[i];
                    
                    if (total > 0.0001f)
                    {
                        for (int i = 0; i < count; i++)
                            outputSplatmap[outputOffset + i] = rawWeights[i] / total;
                    }
                    else
                    {
                        // Default to first layer
                        // outputSplatmap[outputOffset] = 1f;
                        for (int i = 1; i < count; i++)
                            outputSplatmap[outputOffset + i] = 0f;
                    }
                    break;
                }
                    
                case NormalizationMode.MBPainterAlgorithm:
                {
                    WriteMBPainterWeights(rawWeights, outputOffset);
                    break;
                }
                    
                case NormalizationMode.MBNormalized:
                {
                    // First apply painter algorithm to temp storage
                    var painted = new NativeArray<float>(count, Allocator.Temp);
                    ApplyMBPainterToArray(rawWeights, painted);
                    
                    // Then normalize
                    float paintedTotal = 0f;
                    for (int i = 0; i < count; i++)
                        paintedTotal += painted[i];
                    
                    if (paintedTotal > 0.0001f)
                    {
                        for (int i = 0; i < count; i++)
                            outputSplatmap[outputOffset + i] = painted[i] / paintedTotal;
                    }
                    else
                    {
                        outputSplatmap[outputOffset] = 1f;
                        for (int i = 1; i < count; i++)
                            outputSplatmap[outputOffset + i] = 0f;
                    }
                    
                    painted.Dispose();
                    break;
                }
                    
                case NormalizationMode.RawPassthrough:
                {
                    // Write raw weights directly - no normalization
                    for (int i = 0; i < count; i++)
                        outputSplatmap[outputOffset + i] = rawWeights[i];
                    break;
                }
            }
        }
        
        private void WriteMBPainterWeights(NativeArray<float> input, int outputOffset)
        {
            int count = input.Length;
            
            for (int i = 0; i < count; i++)
            {
                if (input[i] < visibilityThreshold)
                {
                    outputSplatmap[outputOffset + i] = 0f;
                    continue;
                }
                
                float visibility = input[i];
                
                for (int j = i + 1; j < count; j++)
                {
                    visibility *= (1f - input[j]);
                    if (visibility < visibilityThreshold)
                    {
                        visibility = 0f;
                        break;
                    }
                }
                
                outputSplatmap[outputOffset + i] = visibility;
            }
        }
        
        private void ApplyMBPainterToArray(NativeArray<float> input, NativeArray<float> output)
        {
            int count = input.Length;
            
            for (int i = 0; i < count; i++)
            {
                if (input[i] < visibilityThreshold)
                {
                    output[i] = 0f;
                    continue;
                }
                
                float visibility = input[i];
                
                for (int j = i + 1; j < count; j++)
                {
                    visibility *= (1f - input[j]);
                    if (visibility < visibilityThreshold)
                    {
                        visibility = 0f;
                        break;
                    }
                }
                
                output[i] = visibility;
            }
        }
    }
    
    /// <summary>
    /// Flattened rule data for job access
    /// </summary>
    public struct RuleData
    {
        public bool active;
        public bool invert;
        public FilterType filter;
        public BlendType blend;
        public float min;
        public float max;
        public int perlinOctaves;
        public float frequency;
        public float lacunarity;
        public float intensity;
        public float contrast;
        public int targetLayerIndex;
        public ImageChannel imageChannel;
        public int curvatureType; // 0=Standard, 1=Profile, 2=Plan
        // Water level rule fields
        public bool useShorelineDistance;
        public float maxShorelineDistance;
    }
    
    #endregion

    #region Base/Overlay Block Management
    
    /// <summary>
    /// Clears only Base block layers, preserving all Overlay layers.
    /// Called by regenerator before rebuilding base layers from hash.
    /// </summary>
    public void ClearBaseLayers()
    {
        layers.RemoveAll(l => l.block == LayerBlock.Base);
        Debug.Log($"[MBTerrainDecorator] Cleared base layers. {layers.Count} overlay layers preserved.");
    }
    
    /// <summary>
    /// Gets all overlay layers (for preservation during regeneration).
    /// </summary>
    public List<Layers> GetOverlayLayers()
    {
        return layers.Where(l => l.block == LayerBlock.Overlay).ToList();
    }
    
    /// <summary>
    /// Gets all base layers.
    /// </summary>
    public List<Layers> GetBaseLayers()
    {
        return layers.Where(l => l.block == LayerBlock.Base).ToList();
    }
    
    /// <summary>
    /// Gets the index where overlay layers start (after all base layers).
    /// </summary>
    public int GetOverlayStartIndex()
    {
        for (int i = 0; i < layers.Count; i++)
        {
            if (layers[i].block == LayerBlock.Overlay)
                return i;
        }
        return layers.Count;
    }
    
    /// <summary>
    /// Rebuilds base layers from regenerator while preserving overlay layers.
    /// This is the main entry point for the regenerator.
    /// 
    /// Usage: 
    ///   decorator.RebuildBaseLayers(newBaseLayers);
    ///   // overlay layers are untouched
    /// </summary>
    public void RebuildBaseLayers(List<Layers> newBaseLayers)
    {
        // Save overlay layers
        var overlayLayers = GetOverlayLayers();
        
        // Clear all layers
        layers.Clear();
        
        // Add new base layers first (they process first in the pipeline)
        foreach (var baseLayer in newBaseLayers)
        {
            baseLayer.block = LayerBlock.Base; // Ensure block is set
            layers.Add(baseLayer);
        }
        
        // Restore overlay layers after base
        foreach (var overlayLayer in overlayLayers)
        {
            layers.Add(overlayLayer);
        }
        
        Debug.Log($"[MBTerrainDecorator] Rebuilt: {newBaseLayers.Count} base + {overlayLayers.Count} overlay layers.");
    }
    
    /// <summary>
    /// Check if any active base layers exist.
    /// </summary>
    public bool HasActiveBaseLayers()
    {
        return layers.Any(l => l.active && l.block == LayerBlock.Base);
    }
    
    /// <summary>
    /// Check if any active overlay layers exist.
    /// </summary>
    public bool HasActiveOverlayLayers()
    {
        return layers.Any(l => l.active && l.block == LayerBlock.Overlay);
    }
    
    /// <summary>
    /// Returns true if a vegetation mask texture is assigned and strength > 0.
    /// </summary>
    public bool HasVegetationMask()
    {
        return vegetationMaskTexture != null && vegetationMaskStrength > 0f;
    }
    
    /// <summary>
    /// Bake the vegetation mask texture into a flat float array at alphamap resolution.
    /// Call once before overlay compositing during Decorate().
    /// </summary>
    private void BakeVegetationMask()
    {
        cachedVegetationMask = null;
        if (!HasVegetationMask()) return;
        
        int totalPixels = alphamapWidth * alphamapHeight;
        cachedVegetationMask = new float[totalPixels];
        
        // Read texture pixels
        Color[] pixels = vegetationMaskTexture.GetPixels();
        int texW = vegetationMaskTexture.width;
        int texH = vegetationMaskTexture.height;
        
        for (int y = 0; y < alphamapHeight; y++)
        {
            for (int x = 0; x < alphamapWidth; x++)
            {
                // Sample texture with bilinear-ish nearest lookup
                float u = x / (float)(alphamapWidth - 1);
                float v = y / (float)(alphamapHeight - 1);
                int tx = Mathf.Clamp(Mathf.FloorToInt(u * (texW - 1)), 0, texW - 1);
                int ty = Mathf.Clamp(Mathf.FloorToInt(v * (texH - 1)), 0, texH - 1);
                
                Color c = pixels[tx + ty * texW];
                float val = vegetationMaskChannel switch
                {
                    ImageChannel.r => c.r,
                    ImageChannel.g => c.g,
                    ImageChannel.b => c.b,
                    ImageChannel.a => c.a,
                    _ => c.r
                };
                
                if (vegetationMaskInvert) val = 1f - val;
                
                cachedVegetationMask[x + y * alphamapWidth] = val * vegetationMaskStrength;
            }
        }
        
        Debug.Log($"[MBTerrainDecorator] Vegetation mask baked: {texW}x{texH} → {alphamapWidth}x{alphamapHeight}, channel={vegetationMaskChannel}, strength={vegetationMaskStrength}");
    }
    
    /// <summary>
    /// Get vegetation mask value at a pixel position. Returns 0 if no mask.
    /// </summary>
    public float GetVegetationMaskAt(int x, int y)
    {
        if (cachedVegetationMask == null) return 0f;
        int idx = x + y * alphamapWidth;
        if (idx < 0 || idx >= cachedVegetationMask.Length) return 0f;
        return cachedVegetationMask[idx];
    }
    
    #endregion

    #region Original Methods (for fallback)
    
    public float CalculateWeigth(float val, float min, float max, float falloff)
    {
        float weight = 0;
        
        if (val > min + falloff / 2f && val <= max - falloff / 2f)
        {
            weight = 1f;
        }
        else if (val < min + falloff / 2f)
        {
            weight = (val - (min - falloff / 2)) / falloff;
        }
        else if (val > max - falloff / 2f)
        {
            weight = 1 - (val - (max - falloff / 2f)) / falloff;
        }
        
        return weight;
    }
    
    public float GetWeight(int index, int x, int y)
    {
        // Use cached splatmaps if available
        if (cachedSplatmaps.IsCreated)
        {
            int idx = (x + y * alphamapWidth) * textureLayerCount + index;
            return cachedSplatmaps[idx];
        }
        
        // Fallback to direct read
        float[,,] splatmapData = t.terrainData.GetAlphamaps(x, y, 1, 1);
        return splatmapData[0, 0, index];
    }
    
    public float ProPerlin(float x, float y, float frequency, float lacunarity,int perlinOctaves)
    {
        float total = 0;
        float _frequency = frequency;
        float amplitude = 1f;
        float persistence = 0.5f;
        float totalAmplitude = 0;
        
        for (int i = 0; i < perlinOctaves; i++)
        {
            total += Mathf.PerlinNoise(x * _frequency, y * _frequency) * amplitude;
            totalAmplitude += amplitude;
            amplitude *= persistence;
            _frequency *= lacunarity;
        }
        
        return total / totalAmplitude;
    }
    
    public float[] ApplyMBPainterAlgorithm(float[] layerIntensities)
    {
        int count = layerIntensities.Length;
        float[] visibilities = new float[count];
        
        for (int i = 0; i < count; i++)
        {
            if (layerIntensities[i] < visibilityThreshold)
            {
                visibilities[i] = 0f;
                continue;
            }
            
            float visibility = layerIntensities[i];
            
            for (int j = i + 1; j < count; j++)
            {
                visibility *= (1f - layerIntensities[j]);
                
                if (visibility < visibilityThreshold)
                {
                    visibility = 0f;
                    break;
                }
            }
            
            visibilities[i] = visibility;
        }
        
        return visibilities;
    }
    
    public float[] ConvertToSplatmapWeights(float[] rawWeights)
    {
        int count = rawWeights.Length;
        float[] result = new float[count];
        
        switch (normalizationMode)
        {
            case NormalizationMode.SimpleNormalize:
                float total = 0f;
                for (int i = 0; i < count; i++)
                    total += rawWeights[i];
                
                if (total > 0.0001f)
                {
                    for (int i = 0; i < count; i++)
                        result[i] = rawWeights[i] / total;
                }
                break;
                
            case NormalizationMode.MBPainterAlgorithm:
                result = ApplyMBPainterAlgorithm(rawWeights);
                break;
                
            case NormalizationMode.MBNormalized:
                float[] painted = ApplyMBPainterAlgorithm(rawWeights);
                float paintedTotal = 0f;
                for (int i = 0; i < count; i++)
                    paintedTotal += painted[i];
                
                if (paintedTotal > 0.0001f)
                {
                    for (int i = 0; i < count; i++)
                        result[i] = painted[i] / paintedTotal;
                }
                break;
        }
        
        return result;
    }
    
    public float ApplyOcclusionBlend(float currentWeight, float newWeight, float intensity)
    {
        float occludedOld = currentWeight * (1f - newWeight * intensity);
        float addedNew = newWeight * intensity;
        return Mathf.Clamp01(occludedOld + addedNew);
    }
    
    #endregion

    #region Filter Processing
    
    public void ProcessGeneratorFilters()
    {
#if UNITY_EDITOR
        GetTerrain();
        int width = t.terrainData.alphamapWidth;
        int height = t.terrainData.alphamapHeight;

        for (int layerNo = 0; layerNo < layers.Count; layerNo++)
        {
            if (!layers[layerNo].active) continue;
            
            for (int i = 0; i < layers[layerNo].rules.Count; i++)
            {
                var rule = layers[layerNo].rules[i];
                if (!rule.active || rule.filter != FilterType.generator) continue;
                
                EditorUtility.DisplayProgressBar("Prepare", "Preparing generator layers", 
                    i / (float)layers[layerNo].rules.Count);

                if (rule.generatorAsset == null) continue;
                
                var path = AssetDatabase.GetAssetPath(rule.generatorAsset);
                float[,] layer = NativeTerrainUtils.ReadSplatmapLayer(path);
                
                if (layer == null) continue;
                
                if (rule.invert)
                    layer = HeightmapHelper.InverseHeightmap(layer);
                
                ProcessRuleMap(rule, layer, width, height);
            }
        }
        
        EditorUtility.ClearProgressBar();
#endif
    }
    
    public void ProcessPGMFilters()
    {
#if UNITY_EDITOR
        GetTerrain();
        int width = t.terrainData.alphamapWidth;
        int height = t.terrainData.alphamapHeight;

        for (int layerNo = 0; layerNo < layers.Count; layerNo++)
        {
            if (!layers[layerNo].active) continue;
            
            for (int i = 0; i < layers[layerNo].rules.Count; i++)
            {
                var rule = layers[layerNo].rules[i];
                if (!rule.active || rule.filter != FilterType.pgm || rule.pgmAsset == null) continue;
                
                EditorUtility.DisplayProgressBar("Prepare", "Preparing PGM layers", 
                    i / (float)layers[layerNo].rules.Count);

                var path = AssetDatabase.GetAssetPath(rule.pgmAsset);
                float[,] layer = PgmHelper.ReadPgm(path);

                if (layer == null) continue;
                
                if (rule.invert)
                    layer = HeightmapHelper.InverseHeightmap(layer);
                
                layer = HeightmapHelper.FlipHeightMapHorizontally(layer);

                var hash = GetComponent<LayeredHeightmapGenerator>()?.CurrentTerrainHash;
                if (!string.IsNullOrEmpty(hash))
                {
                    var data = MBTerrainGeneratorHelpers.ParseTerrainCode(hash);
                    var geoData = MBTerrainGeneratorHelpers.CalculateTerrainGeometryData(data.SizeX, data.SizeY, data.PolygonSize);
                    layer = HeightmapHelper.ClampToGeometryData(layer, geoData);
                }
                
                ProcessRuleMap(rule, layer, width, height);
            }
        }
        
        EditorUtility.ClearProgressBar();
#endif
    }
    
    public void ProcessTextureFilters()
    {
#if UNITY_EDITOR
        GetTerrain();
        int width = t.terrainData.alphamapWidth;
        int height = t.terrainData.alphamapHeight;

        for (int layerNo = 0; layerNo < layers.Count; layerNo++)
        {
            if (!layers[layerNo].active) continue;
        
            for (int i = 0; i < layers[layerNo].rules.Count; i++)
            {
                var rule = layers[layerNo].rules[i];
                if (!rule.active || rule.filter != FilterType.texture || rule.texture == null) continue;
            
                Texture2D tex = rule.texture;
            
                // Convert texture to float[,] array
                int texWidth = tex.width;
                int texHeight = tex.height;
                float[,] layer = new float[texWidth, texHeight];
                Color[] pixels = tex.GetPixels();
            
                for (int y = 0; y < texHeight; y++)
                {
                    for (int x = 0; x < texWidth; x++)
                    {
                        Color c = pixels[x + y * texWidth];
                        layer[x, y] = rule.imageChannel switch
                        {
                            ImageChannel.r => c.r,
                            ImageChannel.g => c.g,
                            ImageChannel.b => c.b,
                            ImageChannel.a => c.a,
                            _ => c.r
                        };
                    }
                }
            
                if (rule.invert)
                    layer = HeightmapHelper.InverseHeightmap(layer);

                layer = HeightmapHelper.RotateHeightMap(layer,HeightmapHelper.Rotation.R270);
                layer = HeightmapHelper.FlipHeightMapVertically(layer);
                // Use ProcessRuleMap to properly resize and reindex
                ProcessRuleMap(rule, layer, width, height);
            }
        }
#endif
    }
    
    public void ProcessWarbandFilters()
    {
#if UNITY_EDITOR
        GetTerrain();
        int width = t.terrainData.alphamapWidth;
        int height = t.terrainData.alphamapHeight;
        
        string terrainCode = "";
        // Try to find the code from FloraConfig or other sources? 
        // For now, we look for FloraPopulatorSubTab logic or just a field on this component if we added one?
        // Actually, better to look for FloraPopulatorConfig or MBTerrainGeneratorData.
        
        // Let's check if we can get it from FloraPopulatorConfig via asset database
        // Or maybe add a field to MBTerrainDecorator for "Warband Code" override?
        // The user said "sync with terrain assets". 
        // MBEditor.Tools.Flora.Logic.WarbandFloraGenerator needs a code.
        
        // Strategy: Use the "Generator Asset" field in the rule to store the code string? No, that's a TextAsset.
        // We can look for a component "FloraPopulatorConfig" in the project?
        // Or, we can use the "Generator Hash" from LayeredHeightmapGenerator if present?
        var layeredGen = GetComponent<LayeredHeightmapGenerator>();
        if (layeredGen != null && !string.IsNullOrEmpty(layeredGen.CurrentTerrainHash))
        {
            terrainCode = layeredGen.CurrentTerrainHash;
        }
        
        // Fallback: Check if there's a global config or just use default?
        // If empty, we can't generate.
        if (string.IsNullOrEmpty(terrainCode))
        {
            // Try to find the config in the scene or assume user has to provide it via LayeredHeightmapGenerator
            // or we add a field to this class.
            // Let's assume LayeredHeightmapGenerator logic for now as it seems to be the main terrain generator.
             Debug.LogWarning("MBTerrainDecorator: No Warband Terrain Code found. Ensure LayeredHeightmapGenerator has a hash.");
             return;
        }

        for (int layerNo = 0; layerNo < layers.Count; layerNo++)
        {
            if (!layers[layerNo].active) continue;
            
            for (int i = 0; i < layers[layerNo].rules.Count; i++)
            {
                var rule = layers[layerNo].rules[i];
                if (!rule.active || rule.filter != FilterType.warband) continue;
                
                EditorUtility.DisplayProgressBar("Prepare", "Calculating Warband Intensity...", 
                    i / (float)layers[layerNo].rules.Count);

                // Map ImageChannel to WarbandChannel
                // R = Earth, G = Green, B = RiverBed
                MBEditor.Tools.Flora.Logic.WarbandFloraGenerator.WarbandChannel channel = MBEditor.Tools.Flora.Logic.WarbandFloraGenerator.WarbandChannel.Earth;
                if (rule.imageChannel == ImageChannel.g) channel = MBEditor.Tools.Flora.Logic.WarbandFloraGenerator.WarbandChannel.Green;
                if (rule.imageChannel == ImageChannel.b) channel = MBEditor.Tools.Flora.Logic.WarbandFloraGenerator.WarbandChannel.RiverBed;
                
                float[,] map = MBEditor.Tools.Flora.Logic.WarbandFloraGenerator.GenerateIntensityMap(t, width, height, terrainCode, channel);
                
                if (rule.invert)
                    map = HeightmapHelper.InverseHeightmap(map); // Assuming helper exists, or manual invert
                
                // ProcessRuleMap handles scaling/mapping to rule.map
                ProcessRuleMap(rule, map, width, height);
            }
        }
        EditorUtility.ClearProgressBar();
#endif
    }
    
    private void ProcessRuleMap(Rules rule, float[,] layer, int targetWidth, int targetHeight)
    {
        int layerWidth = layer.GetLength(0);
        int layerHeight = layer.GetLength(1);
        
        rule.map = new Color[targetWidth * targetHeight];

        if (targetWidth != layerWidth || targetHeight != layerHeight)
        {
            float ratioX = (layerWidth - 1) / (float)targetWidth;
            float ratioY = (layerHeight - 1) / (float)targetHeight;

            for (int y = 0; y < targetHeight; y++)
            {
                int yy = Mathf.FloorToInt(y * ratioY);
                float yLerp = y * ratioY - yy;
                
                for (int x = 0; x < targetWidth; x++)
                {
                    int xx = Mathf.FloorToInt(x * ratioX);
                    float xLerp = x * ratioX - xx;

                    float bl = layer[xx, yy];
                    float br = (xx + 1 < layerWidth) ? layer[xx + 1, yy] : bl;
                    float tl = (yy + 1 < layerHeight) ? layer[xx, yy + 1] : bl;
                    float tr = (xx + 1 < layerWidth && yy + 1 < layerHeight) ? layer[xx + 1, yy + 1] : bl;

                    float val = Mathf.Lerp(Mathf.Lerp(bl, br, xLerp), Mathf.Lerp(tl, tr, xLerp), yLerp);
                    rule.map[x + y * targetWidth] = new Color(val, val, val, 1f);
                }
            }
        }
        else
        {
            for (int y = 0; y < targetHeight; y++)
            {
                for (int x = 0; x < targetWidth; x++)
                {
                    float val = layer[x, y];
                    rule.map[x + y * targetWidth] = new Color(val, val, val, 1f);
                }
            }
        }
    }
    
    #endregion

    #region Decoration
    
    public void Decorate()
    {
        StartCoroutine(DecorateNow());
    }
    
    public IEnumerator DecorateNow()
    {
#if UNITY_EDITOR
        if (calculating)
            yield break;
            
        calculating = true;
        float startTime = Time.realtimeSinceStartup;
        
        // Cache dimensions
        alphamapWidth = t.terrainData.alphamapWidth;
        alphamapHeight = t.terrainData.alphamapHeight;
        heightMapWidth = t.terrainData.heightmapResolution;
        heightMapHeight = t.terrainData.heightmapResolution;
        textureLayerCount = t.terrainData.terrainLayers.Length;
        
        // Cache terrain geometry for slope/curvature calculation
        cellSizeX = t.terrainData.size.x / (heightMapWidth - 1);
        cellSizeY = t.terrainData.size.z / (heightMapHeight - 1);
        cellSize = (cellSizeX + cellSizeY) / 2f; // Average for curvature
        heightScale = t.terrainData.size.y;
        
        if (clearTrees)
        {
            treePrototypeCount = t.terrainData.treePrototypes.Length;
            t.terrainData.treeInstances = new TreeInstance[0];
        }
        
        // Process filter maps
        ProcessGeneratorFilters();
        ProcessPGMFilters();
        ProcessTextureFilters();
        ProcessWarbandFilters();
        
        // Pre-calculate slope map if using accurate slope and caching
        if (useAccurateSlope && cacheSlopeMap && HasSlopeRules())
        {
            EditorUtility.DisplayProgressBar("Prepare", "Calculating slope map...", 0f);
            PreCalculateSlopeMap();
        }
        
        // Pre-calculate curvature maps if using accurate curvature and caching
        if (useAccurateCurvature && cacheCurvatureMap && HasCurvatureRules())
        {
            EditorUtility.DisplayProgressBar("Prepare", "Calculating curvature maps...", 0.1f);
            PreCalculateCurvatureMap();
        }
        
        // Pre-calculate water level and shoreline distance map if needed
        if (cacheWaterMap && HasWaterLevelRules())
        {
            EditorUtility.DisplayProgressBar("Prepare", "Calculating water level map...", 0.2f);
            PreCalculateWaterMap();
        }
        
        // Initialize layers
        InitializeLayers();
        
        // Bake vegetation mask texture if assigned
        // BakeVegetationMask();
        
        if (useJobSystem)
        {
            yield return StartCoroutine(DecorateWithJobs());
        }
        else
        {
            yield return StartCoroutine(DecorateSequential());
        }
        
        // Process trees (not parallelized - needs random state)
        if (clearTrees)
        {
            ProcessTrees();
        }
        
        // Cleanup
        DisposeNativeArrays();
        
        // Clear caches if not persistent
        if (!cacheSlopeMap)
        {
            ClearSlopeCache();
        }
        if (!cacheCurvatureMap)
        {
            ClearCurvatureCache();
        }
        if (!cacheWaterMap)
        {
            ClearWaterCache();
        }
        
        EditorUtility.ClearProgressBar();
        t.Flush();
        
        Debug.Log($"Decoration completed in {Time.realtimeSinceStartup - startTime:F2}s " +
                  $"(Mode: {normalizationMode}, Jobs: {useJobSystem}, AccurateSlope: {useAccurateSlope}, AccurateCurvature: {useAccurateCurvature})");
        
        calculating = false;
#else
        yield break;
#endif
    }
    
    /// <summary>
    /// Check if any active rules use slope filter.
    /// </summary>
    private bool HasSlopeRules()
    {
        foreach (var layer in layers)
        {
            if (!layer.active) continue;
            foreach (var rule in layer.rules)
            {
                if (rule.active && rule.filter == FilterType.slope)
                    return true;
            }
        }
        return false;
    }
    
    /// <summary>
    /// Check if any active rules use curvature filter.
    /// </summary>
    private bool HasCurvatureRules()
    {
        foreach (var layer in layers)
        {
            if (!layer.active) continue;
            foreach (var rule in layer.rules)
            {
                if (rule.active && rule.filter == FilterType.curvature)
                    return true;
            }
        }
        return false;
    }
    
    private void InitializeLayers()
    {
        for (int layerNo = 0; layerNo < layers.Count; layerNo++)
        {
            layers[layerNo].activeRuleCount = 0;
            layers[layerNo].debugResultWeight = 0;
            layers[layerNo].resultWeight = 0;
            layers[layerNo].correctedResultWeight = 0;
            layers[layerNo].debugCorrectedResultWeight = 0;
            layers[layerNo].treeCount = 0;
            
            for (int i = 0; i < layers[layerNo].rules.Count; i++)
            {
                layers[layerNo].rules[i].debugWeight = 0f;
                if (layers[layerNo].rules[i].active)
                    layers[layerNo].activeRuleCount++;
                layers[layerNo].rules[i].weight = 0f;
            }
        }
    }
    
    private IEnumerator DecorateWithJobs()
    {
        int totalPixels = alphamapWidth * alphamapHeight;
        bool hasBaseLayers = HasActiveBaseLayers();
        bool hasOverlayLayers = HasActiveOverlayLayers();
        
        // Allocate shared native arrays
        cachedHeights = new NativeArray<float>(heightMapWidth * heightMapHeight, Allocator.TempJob);
        cachedSplatmaps = new NativeArray<float>(totalPixels * textureLayerCount, Allocator.TempJob);
        outputSplatmap = new NativeArray<float>(totalPixels * textureLayerCount, Allocator.TempJob);
        
        // Cache height data
        float[,] heights = t.terrainData.GetHeights(0, 0, heightMapWidth, heightMapHeight);
        for (int y = 0; y < heightMapHeight; y++)
            for (int x = 0; x < heightMapWidth; x++)
                cachedHeights[y * heightMapWidth + x] = heights[y, x];
        
        // Cache existing splatmaps
        float[,,] splatmaps = t.terrainData.GetAlphamaps(0, 0, alphamapWidth, alphamapHeight);
        for (int y = 0; y < alphamapHeight; y++)
            for (int x = 0; x < alphamapWidth; x++)
                for (int l = 0; l < textureLayerCount; l++)
                    cachedSplatmaps[(x + y * alphamapWidth) * textureLayerCount + l] = splatmaps[x, y, l];
        
        // Cache slope data
        if (useAccurateSlope && slopeCache != null)
        {
            cachedSlopes = new NativeArray<float>(heightMapWidth * heightMapHeight, Allocator.TempJob);
            for (int y = 0; y < heightMapHeight; y++)
                for (int x = 0; x < heightMapWidth; x++)
                    cachedSlopes[y * heightMapWidth + x] = slopeCache.SlopesDegrees[x, y];
        }
        else cachedSlopes = new NativeArray<float>(0, Allocator.TempJob);
        
        // Cache curvature data
        if (useAccurateCurvature && curvatureCache != null)
        {
            int curvatureSize = heightMapWidth * heightMapHeight;
            cachedCurvatureStandard = new NativeArray<float>(curvatureSize, Allocator.TempJob);
            cachedCurvatureProfile = new NativeArray<float>(curvatureSize, Allocator.TempJob);
            cachedCurvaturePlan = new NativeArray<float>(curvatureSize, Allocator.TempJob);
            for (int y = 0; y < heightMapHeight; y++)
                for (int x = 0; x < heightMapWidth; x++)
                {
                    int idx = y * heightMapWidth + x;
                    cachedCurvatureStandard[idx] = curvatureCache.StandardNormalized[y, x];
                    cachedCurvatureProfile[idx] = curvatureCache.ProfileNormalized[y, x];
                    cachedCurvaturePlan[idx] = curvatureCache.PlanNormalized[y, x];
                }
        }
        else
        {
            cachedCurvatureStandard = new NativeArray<float>(0, Allocator.TempJob);
            cachedCurvatureProfile = new NativeArray<float>(0, Allocator.TempJob);
            cachedCurvaturePlan = new NativeArray<float>(0, Allocator.TempJob);
        }
        
        // Cache water shoreline distance data
        if (waterCache != null)
        {
            int waterSize = heightMapWidth * heightMapHeight;
            cachedWaterShoreDistances = new NativeArray<float>(waterSize, Allocator.TempJob);
            for (int y = 0; y < heightMapHeight; y++)
                for (int x = 0; x < heightMapWidth; x++)
                    cachedWaterShoreDistances[y * heightMapWidth + x] = waterCache.ShorelineDistances[y, x];
        }
        else cachedWaterShoreDistances = new NativeArray<float>(0, Allocator.TempJob);
        
        // Helper to create a DecorateJob with common params
        DecorateJob CreateJob(NativeArray<RuleData> rd, NativeArray<int> lro, NativeArray<int> lrc,
            NativeArray<int> li, NativeArray<bool> la, NativeArray<float> arm,
            NativeArray<int> rmo, NativeArray<int> rms, NormalizationMode nm)
        {
            return new DecorateJob
            {
                alphamapWidth = alphamapWidth, alphamapHeight = alphamapHeight,
                heightMapWidth = heightMapWidth, heightMapHeight = heightMapHeight,
                textureLayerCount = textureLayerCount, fallOffDistance = fallOffDistance,
                normMode = nm, visibilityThreshold = visibilityThreshold,
                useAccurateSlope = useAccurateSlope, cellSizeX = cellSizeX, cellSizeY = cellSizeY,
                heightScale = heightScale, slopeInDegrees = slopeInDegrees,
                useAccurateCurvature = useAccurateCurvature, cellSize = cellSize,
                curvatureNormalized = curvatureNormalized,
                waterLevel = waterLevel, terrainY = transform.position.y,
                waterShoreDistances = cachedWaterShoreDistances,
                heights = cachedHeights, slopes = cachedSlopes,
                curvatureStandard = cachedCurvatureStandard,
                curvatureProfile = cachedCurvatureProfile,
                curvaturePlan = cachedCurvaturePlan,
                existingSplatmaps = cachedSplatmaps,
                ruleData = rd, layerRuleOffsets = lro, layerRuleCounts = lrc,
                layerIndices = li, layerActive = la, allRuleMaps = arm,
                ruleMapOffsets = rmo, ruleMapSizes = rms, outputSplatmap = outputSplatmap
            };
        }
        
        void DisposeJobArrays(NativeArray<RuleData> rd, NativeArray<int> lro, NativeArray<int> lrc,
            NativeArray<int> li, NativeArray<bool> la, NativeArray<float> arm,
            NativeArray<int> rmo, NativeArray<int> rms)
        {
            rd.Dispose(); lro.Dispose(); lrc.Dispose(); li.Dispose();
            la.Dispose(); arm.Dispose(); rmo.Dispose(); rms.Dispose();
        }
        
        // PASS 1: BASE BLOCK
        if (hasBaseLayers)
        {
            PrepareJobDataForBlock(LayerBlock.Base,
                out var rd, out var lro, out var lrc, out var li, out var la,
                out var arm, out var rmo, out var rms);
            
            var baseJob = CreateJob(rd, lro, lrc, li, la, arm, rmo, rms, normalizationMode);
            
            EditorUtility.DisplayProgressBar("Decorating", "Base block (parallel)...", 0.25f);
            var handle = baseJob.Schedule(totalPixels, jobBatchSize);
            while (!handle.IsCompleted) yield return null;
            handle.Complete();
            
            DisposeJobArrays(rd, lro, lrc, li, la, arm, rmo, rms);
        }
        
        // PASS 2: OVERLAY BLOCK - composite over base
        if (hasOverlayLayers)
        {
            bool hasVegMask = HasVegetationMask();
            
            // Run overlay layers through job to get their raw weights
            var overlayOutput = new NativeArray<float>(totalPixels * textureLayerCount, Allocator.TempJob);
            
            // Temporarily swap output target
            var savedOutput = outputSplatmap;
            
            PrepareJobDataForBlock(LayerBlock.Overlay,
                out var ord, out var olro, out var olrc, out var oli, out var ola,
                out var oarm, out var ormo, out var orms);
            
            // Create overlay job writing to overlayOutput - raw weights, no normalization
            var overlayJob = CreateJob(ord, olro, olrc, oli, ola, oarm, ormo, orms, NormalizationMode.RawPassthrough);
            overlayJob.outputSplatmap = overlayOutput;
            
            EditorUtility.DisplayProgressBar("Decorating", "Overlay block (parallel)...", 0.6f);
            var oHandle = overlayJob.Schedule(totalPixels, jobBatchSize);
            while (!oHandle.IsCompleted) yield return null;
            oHandle.Complete();
            
            // Composite overlay onto base
            EditorUtility.DisplayProgressBar("Decorating", "Compositing overlay...", 0.85f);
            
            var overlayLayerInfo = new List<(int layerIndex, float opacity, OverlayBlendMode mode)>();
            foreach (var layer in layers)
            {
                if (layer.active && layer.block == LayerBlock.Overlay && layer.layerIndex < textureLayerCount)
                    overlayLayerInfo.Add((layer.layerIndex, layer.overlayOpacity, layer.overlayBlendMode));
            }
            
            for (int pixelIndex = 0; pixelIndex < totalPixels; pixelIndex++)
            {
                int offset = pixelIndex * textureLayerCount;
                float[] baseWeights = new float[textureLayerCount];
                for (int i = 0; i < textureLayerCount; i++)
                    baseWeights[i] = outputSplatmap[offset + i];
                
                // Vegetation mask: attenuate all overlay weights at this pixel
                int px = pixelIndex % alphamapWidth;
                int py = pixelIndex / alphamapWidth;
                float vegMultiplier = hasVegMask ? (1f - GetVegetationMaskAt(px, py)) : 1f;
                
                foreach (var (layerIdx, opacity, mode) in overlayLayerInfo)
                {
                    float overlayWeight = overlayOutput[offset + layerIdx] * opacity * vegMultiplier;
                    if (overlayWeight < visibilityThreshold) continue;
                    ApplyOverlayToBaseWeights(baseWeights, layerIdx, overlayWeight, mode);
                }
                
                if (renormalizeAfterOverlay)
                {
                    float total = 0f;
                    for (int i = 0; i < textureLayerCount; i++) total += baseWeights[i];
                    if (total > 0.0001f)
                        for (int i = 0; i < textureLayerCount; i++) baseWeights[i] /= total;
                }
                
                for (int i = 0; i < textureLayerCount; i++)
                    outputSplatmap[offset + i] = baseWeights[i];
            }
            
            overlayOutput.Dispose();
            DisposeJobArrays(ord, olro, olrc, oli, ola, oarm, ormo, orms);
        }
        
        // Copy results to terrain
        EditorUtility.DisplayProgressBar("Decorating", "Applying results...", 0.9f);
        map = new float[alphamapWidth, alphamapHeight, textureLayerCount];
        for (int y = 0; y < alphamapHeight; y++)
            for (int x = 0; x < alphamapWidth; x++)
                for (int l = 0; l < textureLayerCount; l++)
                    map[x, y, l] = outputSplatmap[(x + y * alphamapWidth) * textureLayerCount + l];
        
        t.terrainData.SetAlphamaps(0, 0, map);
    }
    
    private void PrepareJobData(out NativeArray<RuleData> ruleData, 
        out NativeArray<int> layerRuleOffsets, out NativeArray<int> layerRuleCounts,
        out NativeArray<int> layerIndices, out NativeArray<bool> layerActive,
        out NativeArray<float> allRuleMaps, out NativeArray<int> ruleMapOffsets, 
        out NativeArray<int> ruleMapSizes)
    {
        PrepareJobDataForBlock(null, out ruleData, out layerRuleOffsets, out layerRuleCounts,
            out layerIndices, out layerActive, out allRuleMaps, out ruleMapOffsets, out ruleMapSizes);
    }
    
    /// <summary>
    /// Prepare job data filtered by block type. If blockFilter is null, includes all layers.
    /// </summary>
    private void PrepareJobDataForBlock(LayerBlock? blockFilter,
        out NativeArray<RuleData> ruleData, 
        out NativeArray<int> layerRuleOffsets, out NativeArray<int> layerRuleCounts,
        out NativeArray<int> layerIndices, out NativeArray<bool> layerActive,
        out NativeArray<float> allRuleMaps, out NativeArray<int> ruleMapOffsets, 
        out NativeArray<int> ruleMapSizes)
    {
        var filteredLayers = blockFilter.HasValue 
            ? layers.Where(l => l.block == blockFilter.Value).ToList() 
            : layers;
        
        // Count total rules and map data
        int totalRules = 0;
        int totalMapSize = 0;
        
        foreach (var layer in filteredLayers)
        {
            totalRules += layer.rules.Count;
            foreach (var rule in layer.rules)
            {
                if (rule.map != null)
                    totalMapSize += rule.map.Length;
            }
        }
        
        int filteredCount = filteredLayers.Count();
        
        // Allocate arrays
        ruleData = new NativeArray<RuleData>(totalRules > 0 ? totalRules : 1, Allocator.TempJob);
        layerRuleOffsets = new NativeArray<int>(filteredCount > 0 ? filteredCount : 1, Allocator.TempJob);
        layerRuleCounts = new NativeArray<int>(filteredCount > 0 ? filteredCount : 1, Allocator.TempJob);
        layerIndices = new NativeArray<int>(filteredCount > 0 ? filteredCount : 1, Allocator.TempJob);
        layerActive = new NativeArray<bool>(filteredCount > 0 ? filteredCount : 1, Allocator.TempJob);
        allRuleMaps = new NativeArray<float>(totalMapSize > 0 ? totalMapSize : 1, Allocator.TempJob);
        ruleMapOffsets = new NativeArray<int>(totalRules > 0 ? totalRules : 1, Allocator.TempJob);
        ruleMapSizes = new NativeArray<int>(totalRules > 0 ? totalRules : 1, Allocator.TempJob);
        
        // Fill data
        int ruleIdx = 0;
        int mapOffset = 0;
        int l = 0;
        
        foreach (var layer in filteredLayers)
        {
            layerRuleOffsets[l] = ruleIdx;
            layerRuleCounts[l] = layer.rules.Count;
            layerIndices[l] = layer.layerIndex;
            layerActive[l] = layer.active;
            
            for (int r = 0; r < layer.rules.Count; r++)
            {
                var rule = layer.rules[r];
                
                ruleData[ruleIdx] = new RuleData
                {
                    active = rule.active,
                    invert = rule.invert,
                    filter = rule.filter,
                    blend = rule.blend,
                    min = rule.min,
                    max = rule.max,
                    frequency = rule.frequency,
                    lacunarity = rule.lacunarity,
                    perlinOctaves = rule.perlinOctaves,
                    intensity = rule.intensity,
                    contrast = rule.contrast,
                    targetLayerIndex = rule.targetLayerIndex,
                    imageChannel = rule.imageChannel,
                    curvatureType = (int)rule.curvatureType,
                    useShorelineDistance = rule.useShorelineDistance,
                    maxShorelineDistance = rule.maxShorelineDistance
                };
                
                if (rule.map != null && rule.map.Length > 0)
                {
                    ruleMapOffsets[ruleIdx] = mapOffset;
                    ruleMapSizes[ruleIdx] = rule.map.Length;
                    
                    for (int m = 0; m < rule.map.Length; m++)
                    {
                        // Extract channel based on imageChannel
                        float val = rule.imageChannel switch
                        {
                            ImageChannel.r => rule.map[m].r,
                            ImageChannel.g => rule.map[m].g,
                            ImageChannel.b => rule.map[m].b,
                            ImageChannel.a => rule.map[m].a,
                            _ => rule.map[m].r
                        };
                        allRuleMaps[mapOffset + m] = val;
                    }
                    
                    mapOffset += rule.map.Length;
                }
                else
                {
                    ruleMapOffsets[ruleIdx] = 0;
                    ruleMapSizes[ruleIdx] = 0;
                }
                
                ruleIdx++;
            }
            l++;
        }
    }
    
    /// <summary>
    /// Convenience overload with non-nullable block filter.
    /// </summary>
    private void PrepareJobDataForBlock(LayerBlock block,
        out NativeArray<RuleData> ruleData,
        out NativeArray<int> layerRuleOffsets, out NativeArray<int> layerRuleCounts,
        out NativeArray<int> layerIndices, out NativeArray<bool> layerActive,
        out NativeArray<float> allRuleMaps, out NativeArray<int> ruleMapOffsets,
        out NativeArray<int> ruleMapSizes)
    {
        PrepareJobDataForBlock((LayerBlock?)block, out ruleData, out layerRuleOffsets, out layerRuleCounts,
            out layerIndices, out layerActive, out allRuleMaps, out ruleMapOffsets, out ruleMapSizes);
    }
    
    private IEnumerator DecorateSequential()
    {
        // Cache data
        float[,] heights = t.terrainData.GetHeights(0, 0, heightMapWidth, heightMapHeight);
        map = new float[alphamapWidth, alphamapHeight, textureLayerCount];
        
        UnityEngine.Random.InitState(42);
        
        bool hasBaseLayers = HasActiveBaseLayers();
        bool hasOverlayLayers = HasActiveOverlayLayers();
        
        // PASS 1: BASE BLOCK - Engine-accurate generator layers
        if (hasBaseLayers)
        {
            for (int y = 0; y < alphamapHeight; y++)
            {
                if (y % progressUpdateInterval == 0)
                {
                    float progress = y / (float)alphamapHeight * (hasOverlayLayers ? 0.5f : 1f);
                    EditorUtility.DisplayProgressBar("Decorating", $"Base block: row {y}/{alphamapHeight}", progress);
                    
                    if (showProgress)
                    {
                        calculatingPercent = progress;
                        t.terrainData.SetAlphamaps(0, 0, map);
                        yield return null;
                    }
                }
                
                for (int x = 0; x < alphamapWidth; x++)
                {
                    float normX = x / (float)(alphamapWidth - 1);
                    float normY = y / (float)(alphamapHeight - 1);
                    
                    float[] rawWeights = new float[textureLayerCount];
                    
                    ProcessLayersForBlock(heights, normX, normY, x, y, LayerBlock.Base);
                    
                    for (int layerNo = 0; layerNo < layers.Count; layerNo++)
                    {
                        if (!layers[layerNo].active) continue;
                        if (layers[layerNo].block != LayerBlock.Base) continue;
                        if (layers[layerNo].layerIndex >= textureLayerCount) continue;
                        
                        rawWeights[layers[layerNo].layerIndex] += layers[layerNo].resultWeight;
                    }
                    
                    float[] splatWeights = ConvertToSplatmapWeights(rawWeights);
                    
                    for (int i = 0; i < textureLayerCount; i++)
                        map[x, y, i] = splatWeights[i];
                }
            }
        }
        
        // PASS 2: OVERLAY BLOCK - Hand-painted layers over base
        if (hasOverlayLayers)
        {
            bool hasVegMask = HasVegetationMask();
            
            for (int y = 0; y < alphamapHeight; y++)
            {
                if (y % progressUpdateInterval == 0)
                {
                    float progress = 0.5f + (y / (float)alphamapHeight * 0.5f);
                    EditorUtility.DisplayProgressBar("Decorating", $"Overlay block: row {y}/{alphamapHeight}", progress);
                    
                    if (showProgress)
                    {
                        calculatingPercent = progress;
                        t.terrainData.SetAlphamaps(0, 0, map);
                        yield return null;
                    }
                }
                
                for (int x = 0; x < alphamapWidth; x++)
                {
                    float normX = x / (float)(alphamapWidth - 1);
                    float normY = y / (float)(alphamapHeight - 1);
                    
                    // Vegetation mask: attenuate all overlay weights at this pixel
                    float vegMultiplier = hasVegMask ? (1f - GetVegetationMaskAt(x, y)) : 1f;
                    
                    ProcessLayersForBlock(heights, normX, normY, x, y, LayerBlock.Overlay);
                    
                    float[] baseWeights = new float[textureLayerCount];
                    for (int i = 0; i < textureLayerCount; i++)
                        baseWeights[i] = map[x, y, i];
                    
                    for (int layerNo = 0; layerNo < layers.Count; layerNo++)
                    {
                        if (!layers[layerNo].active) continue;
                        if (layers[layerNo].block != LayerBlock.Overlay) continue;
                        if (layers[layerNo].layerIndex >= textureLayerCount) continue;
                        
                        float overlayWeight = layers[layerNo].resultWeight * layers[layerNo].overlayOpacity * vegMultiplier;
                        if (overlayWeight < visibilityThreshold) continue;
                        
                        ApplyOverlayToBaseWeights(baseWeights, layers[layerNo].layerIndex, 
                            overlayWeight, layers[layerNo].overlayBlendMode);
                    }
                    
                    if (renormalizeAfterOverlay)
                    {
                        float total = 0f;
                        for (int i = 0; i < textureLayerCount; i++)
                            total += baseWeights[i];
                        if (total > 0.0001f)
                            for (int i = 0; i < textureLayerCount; i++)
                                baseWeights[i] /= total;
                    }
                    
                    for (int i = 0; i < textureLayerCount; i++)
                        map[x, y, i] = baseWeights[i];
                }
            }
        }
        
        t.terrainData.SetAlphamaps(0, 0, map);
    }
    
    /// <summary>
    /// Process layers belonging to a specific block for a single pixel.
    /// </summary>
    private void ProcessLayersForBlock(float[,] heights, float normX, float normY, int x, int y, LayerBlock block)
    {
        for (int layerNo = 0; layerNo < layers.Count; layerNo++)
        {
            if (!layers[layerNo].active) continue;
            if (layers[layerNo].block != block) continue;
            
            float layerResultWeight = 0f;
            bool firstRule = true;
            
            for (int i = 0; i < layers[layerNo].rules.Count; i++)
            {
                if (!layers[layerNo].rules[i].active) continue;
                
                float weight = 0f;
                var rule = layers[layerNo].rules[i];
                
                switch (rule.filter)
                {
                    case FilterType.height:
                        int hx = Mathf.FloorToInt(normY * (heightMapHeight - 1));
                        int hy = Mathf.FloorToInt(normX * (heightMapWidth - 1));
                        float heightVal = heights[hx, hy];
                        weight = CalculateWeigth(heightVal, rule.min, rule.max, fallOffDistance / 100f);
                        break;
                    case FilterType.slope:
                        weight = CalculateSlopeWeight(normX, normY, rule.min, rule.max);
                        break;
                    case FilterType.curvature:
                        weight = CalculateCurvatureWeight(normX, normY, rule.min, rule.max, rule.curvatureType);
                        break;
                    case FilterType.noise:
                        weight = ProPerlin(normX, normY, rule.frequency, rule.lacunarity, rule.perlinOctaves);
                        break;
                    case FilterType.texture:
                    case FilterType.pgm:
                    case FilterType.generator:
                        if (rule.map != null && rule.map.Length > 0)
                        {
                            int idx = x + y * alphamapWidth;
                            if (idx < rule.map.Length)
                            {
                                Color c = rule.map[idx];
                                weight = rule.imageChannel switch
                                {
                                    ImageChannel.r => c.r, ImageChannel.g => c.g,
                                    ImageChannel.b => c.b, ImageChannel.a => c.a, _ => c.r
                                };
                            }
                        }
                        break;
                    case FilterType.layer:
                        if (rule.targetLayerIndex < textureLayerCount)
                            weight = GetWeight(rule.targetLayerIndex, x, y);
                        break;
                    case FilterType.waterLevel:
                        weight = CalculateWaterLevelWeight(normX, normY, rule.min, rule.max,
                                                           rule.useShorelineDistance, rule.maxShorelineDistance);
                        break;
                }
                
                if (rule.intensity < 0) weight = 1 - weight;
                
                if (rule.invert)
                    weight = 1f - weight;
                
                weight = (weight - 0.5f) * (rule.contrast + 1) + 0.5f;
                weight *= Mathf.Abs(rule.intensity);
                weight = Mathf.Clamp(weight, 0, 1);
                rule.weight = weight;
                
                if (firstRule) { layerResultWeight = weight; firstRule = false; }
                else
                {
                    layerResultWeight = rule.blend switch
                    {
                        BlendType.normal => weight,
                        BlendType.add => layerResultWeight + weight,
                        BlendType.sub => layerResultWeight - weight,
                        BlendType.mul => layerResultWeight * weight,
                        BlendType.min => Mathf.Min(layerResultWeight, weight),
                        BlendType.max => Mathf.Max(layerResultWeight, weight),
                        BlendType.occlusion => ApplyOcclusionBlend(layerResultWeight, weight, 1f),
                        _ => layerResultWeight
                    };
                }
            }
            layers[layerNo].resultWeight = Mathf.Clamp(layerResultWeight, 0f, 1f);
        }
    }
    
    /// <summary>
    /// Apply overlay layer weight onto base splatmap weights.
    /// </summary>
    private void ApplyOverlayToBaseWeights(float[] baseWeights, int targetIdx, float overlayWeight, OverlayBlendMode mode)
    {
        switch (mode)
        {
            case OverlayBlendMode.Additive:
                baseWeights[targetIdx] += overlayWeight;
                break;
                
            case OverlayBlendMode.Lerp:
                for (int i = 0; i < baseWeights.Length; i++)
                {
                    float target = (i == targetIdx) ? 1f : 0f;
                    baseWeights[i] = Mathf.Lerp(baseWeights[i], target, overlayWeight);
                }
                break;
                
            case OverlayBlendMode.Replace:
                float scaleDown = 1f - overlayWeight;
                for (int i = 0; i < baseWeights.Length; i++)
                {
                    if (i == targetIdx) baseWeights[i] = overlayWeight;
                    else baseWeights[i] *= scaleDown;
                }
                break;
                
            case OverlayBlendMode.PainterOcclusion:
                float remaining = 1f - overlayWeight;
                for (int i = 0; i < baseWeights.Length; i++)
                {
                    if (i == targetIdx) baseWeights[i] = baseWeights[i] * remaining + overlayWeight;
                    else baseWeights[i] *= remaining;
                }
                break;
        }
    }
    
    private void ProcessLayersOptimized(float[,] heights, float normX, float normY, int x, int y)
    {
        for (int layerNo = 0; layerNo < layers.Count; layerNo++)
        {
            if (!layers[layerNo].active) continue;
            
            float layerResultWeight = 0f;
            bool firstRule = true;
            
            for (int i = 0; i < layers[layerNo].rules.Count; i++)
            {
                if (!layers[layerNo].rules[i].active) continue;
                
                float weight = 0f;
                var rule = layers[layerNo].rules[i];
                
                switch (rule.filter)
                {
                    case FilterType.height:
                        int hx = Mathf.FloorToInt(normY * (heightMapHeight - 1));
                        int hy = Mathf.FloorToInt(normX * (heightMapWidth - 1));
                        float heightVal = heights[hx, hy];
                        weight = CalculateWeigth(heightVal, rule.min, rule.max, fallOffDistance / 100f);
                        break;
                        
                    case FilterType.slope:
                        // Use proper slope calculation
                        weight = CalculateSlopeWeight(normX, normY, rule.min, rule.max);
                        break;
                        
                    case FilterType.curvature:
                        // Use proper curvature calculation
                        weight = CalculateCurvatureWeight(normX, normY, rule.min, rule.max, rule.curvatureType);
                        break;
                        
                    case FilterType.noise:
                        weight = ProPerlin(normX, normY, rule.frequency, rule.lacunarity,rule.perlinOctaves);
                        break;
                        
                    case FilterType.texture:
                    case FilterType.pgm:
                    case FilterType.generator:
                        if (rule.map != null && rule.map.Length > 0)
                        {
                            int idx = x + y * alphamapWidth;
                            if (idx < rule.map.Length)
                            {
                                Color c = rule.map[idx];
                                weight = rule.imageChannel switch
                                {
                                    ImageChannel.r => c.r,
                                    ImageChannel.g => c.g,
                                    ImageChannel.b => c.b,
                                    ImageChannel.a => c.a,
                                    _ => c.r
                                };
                            }
                        }
                        break;
                        
                    case FilterType.layer:
                        if (rule.targetLayerIndex < textureLayerCount)
                        {
                            weight = GetWeight(rule.targetLayerIndex, x, y);
                        }
                        break;
                    case FilterType.waterLevel:
                        weight = CalculateWaterLevelWeight(normX, normY, rule.min, rule.max,
                                                           rule.useShorelineDistance, rule.maxShorelineDistance);
                        break;
                }
                
                if (rule.intensity < 0)
                    weight = 1 - weight;
                
                if (rule.invert)
                    weight = 1f - weight;
                
                weight = (weight - 0.5f) * (rule.contrast + 1) + 0.5f;
                weight *= Mathf.Abs(rule.intensity);
                weight = Mathf.Clamp(weight, 0, 1);
                
                rule.weight = weight;
                
                if (firstRule)
                {
                    layerResultWeight = weight;
                    firstRule = false;
                }
                else
                {
                    layerResultWeight = rule.blend switch
                    {
                        BlendType.normal => weight,
                        BlendType.add => layerResultWeight + weight,
                        BlendType.sub => layerResultWeight - weight,
                        BlendType.mul => layerResultWeight * weight,
                        BlendType.min => Mathf.Min(layerResultWeight, weight),
                        BlendType.max => Mathf.Max(layerResultWeight, weight),
                        BlendType.occlusion => ApplyOcclusionBlend(layerResultWeight, weight, 1f),
                        _ => layerResultWeight
                    };
                }
            }
            
            layers[layerNo].resultWeight = Mathf.Clamp(layerResultWeight, 0f, 1f);
        }
    }
    
    private void ProcessTrees()
    {
        UnityEngine.Random.InitState(42);
        
        for (int y = 0; y < alphamapHeight; y++)
        {
            for (int x = 0; x < alphamapWidth; x++)
            {
                float normX = x / (float)(alphamapWidth - 1);
                float normY = y / (float)(alphamapHeight - 1);
                
                for (int layerNo = 0; layerNo < layers.Count; layerNo++)
                {
                    if (!layers[layerNo].active) continue;
                    if (layers[layerNo].layerIndex < textureLayerCount) continue;
                    
                    float probability = UnityEngine.Random.Range(0f, 1f);
                    int inc = Mathf.CeilToInt(alphamapWidth / Mathf.Sqrt(layers[layerNo].maximumTreeCount));
                    
                    if (y % inc == 0 && x % inc == 0)
                    {
                        if (layers[layerNo].treeCount < layers[layerNo].maximumTreeCount)
                        {
                            if (layers[layerNo].resultWeight > 0)
                            {
                                int treeIdx = layers[layerNo].layerIndex - textureLayerCount;
                                if (treeIdx >= 0 && treeIdx < treePrototypeCount)
                                {
                                    if (probability < layers[layerNo].probability * layers[layerNo].resultWeight)
                                    {
                                        TreeInstance tree = new TreeInstance();
                                        
                                        float rndPos = UnityEngine.Random.Range(-1f, 1f) / alphamapWidth * 
                                                       layers[layerNo].randomPosition * inc;
                                        float rndRot = UnityEngine.Random.Range(-1f, 1f) * layers[layerNo].randomRotation * 6.283f;
                                        float rndScale = 1f + UnityEngine.Random.Range(0, 1f) * layers[layerNo].randomSize;
                                        
                                        float nx = normY + rndPos;
                                        float ny = normX + rndPos;
                                        
                                        float _height = t.terrainData.GetHeight(
                                            Mathf.FloorToInt(ny * (heightMapHeight - 1)),
                                            Mathf.FloorToInt(nx * (heightMapWidth - 1)));
                                        
                                        tree.position = new Vector3(ny, 
                                            (_height + layers[layerNo].offset) / t.terrainData.heightmapScale.y, nx);
                                        tree.color = Color.Lerp(Color.white, new Color(1, 0.8f, 0), 
                                            UnityEngine.Random.Range(0f, layers[layerNo].randomHealth));
                                        tree.rotation = rndRot;
                                        tree.heightScale = layers[layerNo].height * rndScale;
                                        tree.widthScale = layers[layerNo].width * rndScale;
                                        tree.prototypeIndex = treeIdx;
                                        tree.lightmapColor = Color.white;
                                        layers[layerNo].treeCount++;
                                        t.AddTreeInstance(tree);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    
    private void DisposeNativeArrays()
    {
        if (cachedHeights.IsCreated) cachedHeights.Dispose();
        if (cachedSplatmaps.IsCreated) cachedSplatmaps.Dispose();
        if (cachedSlopes.IsCreated) cachedSlopes.Dispose();
        if (cachedCurvatureStandard.IsCreated) cachedCurvatureStandard.Dispose();
        if (cachedCurvatureProfile.IsCreated) cachedCurvatureProfile.Dispose();
        if (cachedCurvaturePlan.IsCreated) cachedCurvaturePlan.Dispose();
        if (cachedWaterShoreDistances.IsCreated) cachedWaterShoreDistances.Dispose();
        if (outputSplatmap.IsCreated) outputSplatmap.Dispose();
    }
    
    private void OnDestroy()
    {
        DisposeNativeArrays();
    }
    
    #endregion
}
